### ISSUE TITLE
Drag/drop support in conversations

### ISSUE THREAD

**Issue by avaidyam** [avaidyam/Parrot#16]
Example: dragging images/text/links/anything into a conversation view will add them to the message before sending them.

**Comment by avaidyam** [comment]
Added with `DroppableView` -- not yet implemented due to lack of `Service` support.

**Comment by eonist** [comment]
Hey man, great work. Did you make MochaUI? Looks really cool. Love the way you run this project 😻

**Comment by avaidyam** [comment]
@eonist Thanks! I love your work with Element/StyleKit as well! (I think I've read all your blog/discovery posts)

Oh, to answer your question: Yes, Mocha + MochaUI were what I ended up breaking out a lot of custom controls and patches into. There's a deprecated Objective-C version in my repos still too... 😄

**Comment by eonist** [comment]
No way man. That blog  was rambelings of a mad man. Color me impressed. We should definitly collab some day. Im working on making the Element project more functional programming like. And POP. Also adding flexbox to it. Let me know if you have some ideas etc. 🐙

**Comment by avaidyam** [comment]
@eonist Trust me, it took a while to understand, but it helped in quite a few cases. (By the way, it would be much nicer if you styled `Element` to match the default macOS styles lol...)

Yeah, collab is fine! More like let's see where `Mocha/UI` and `Element` go, and see if we can create a _cross-platform protocol-oriented flexbox-layout hardware-accelerated_ UI framework!

**Comment by eonist** [comment]
Definitely. Sharing is ideas across projects. "The style should match macOs". I'm not a designer so I might not notice small things. Or did you mean coding style?

 I'm working a lot on easing the Style setup. So that you can just install and hack away and have solution in no time. Perfect for hackathons etc.  I'm currently working on using the default window shadow but also having the possibility to use your own UI. I have an idea today. And I'm working on a really cool resize demo. With min and max guards for when UI should resize etc. 

Anyways it would be awesome if we found a common place to share ideas / experience.

**Comment by eonist** [comment]
I'm active on https://swift-lang.slack.com

They have PM. You can find me at @eonist 

If you wish.

**Comment by avaidyam** [comment]
Awesome!! I'll follow you and keep in touch lol. Trying to get *off* Slack though 😂

**Comment by eonist** [comment]
Yes slack will ruin us all. I like to think I use it only for PM. Talks later. 😉
